import os,subprocess
from pathlib import Path
P='/data/zhangbenzhuang/miniconda3/envs/test/bin/python'
r=Path('/data/zhangbenzhuang/huawei_sr/runs/SS928-EXTREME-20260927');c=r/'code_snapshot'
cases=['combo_input9_half_aligned16_nearest', 'combo_stats3_relu32_aligned16_half_output_fixed', 'body3_quantsearch', 'cal_front3x1_trained_native4_alignpixel', 'cal_front3x3_trained_native4_alignpixel', 'cal_front3x1_trained_body3_native4_alignpixel', 'cal_front3x1_trained_body2_native4_alignpixel', 'cal_front3x1_trained_body2_native4_alignpixel_outdeconv', 'cal_front3x1_trained_body2_native4_alignpixel_outcascade', 'cal_front3x1_trained_body2_native4_alignpixel_layout16', 'cal_front3x1_trained_body2_native4_alignpixel_layout5', 'cal_front3x1_trained_body2_native4_alignpixel_f32io', 'cal_front3x1_trained_body2_native4_alignpixel_f32in', 'cal_front3x1_trained_body2_native4_alignpixel_f32out', 'cal_front3x1_trained_body2_native4_alignpixel_refpad16', 'cal_front3x1_trained_body2_native4_alignpixel_meanfirst', 'cal_front3x1_trained_body2_native4_alignpixel_refpad16_meanfirst', 'cal_front3x1_trained_body2_native4_alignpixel_refpad16_meanfirst_block16_full', 'cal_front3x1_trained_body2_native4_alignpixel_refpad16_meanfirst_block16_split_full', 'cal_front3x1_trained_body2_native4_alignpixel_refpad16_meanfirst_block16', 'cal_front3x1_trained_body2_native4_alignpixel_refpad16_meanfirst_block16_f32io', 'cal_front3x1_trained_body2_native4_alignpixel_refpad16_meanfirst_block16_full_f32io', 'quarter_w32_3x3_body1_stage1_fusedtail', 'quarter_w32_3x3_body1_qat_w8allpo', 'quarter_w32_3x3_body1_qat_w8allpo_fusedtail', 'cal_graph_quarter_w32_3x3_body1_qat_w8allpo_fusedtail', 'quarter_w32_3x3_body1', 'quarter_w32_3x3_body1_stage1_fusedtail_outdeconv', 'quarter_w32_3x3_body1_stage1_fusedtail_outcascade', 'quarter_w32_3x3_body1_stage1_refpad16_meanfirst_fusedtail', 'quarter_w32_3x3_body1_stage1_layout16_fusedtail', 'quarter_w32_3x3_body1_stage1_layout5_fusedtail', 'quarter_w32_3x3_body1_stage1_fusedtail_f32io', 'quarter_w32_3x3_body1_stage1_fusedtail_block16', 'quarter_w32_3x3_body1_stage1_fusedtail_block16_full', 'quarter_w32_3x3_body1_stage1_fusedtail_block16_split_full', 'cal_front3x1_trained_body3_native4_alignpixel_outdeconv', 'cal_front3x1_trained_body3_native4_alignpixel_outcascade', 'cal_front3x1_trained_body3_native4_alignpixel_f32io', 'cal_front3x1_trained_body3_native4_alignpixel_layout16', 'cal_front3x1_trained_body3_native4_alignpixel_layout5', 'cal_front3x1_trained_body3_native4_alignpixel_refpad16_meanfirst']
for scene in ['ordinary','special']:
 for script,args in [('export_candidates.py',['--tag','final_export','--cases',*cases]),('export_reference_vectors.py',['--cases',*cases]),('export_extra_probes.py',[])]:
  with (r/(scene+'_'+script+'.log')).open('w') as out:subprocess.run([P,str(c/script),'--scene',scene,*args],stdout=out,stderr=subprocess.STDOUT,check=True)
print('ALL_EXPORTS_COMPLETE',flush=True)
