"""Fit the final linear reference convolution exactly on train contexts."""
import argparse,fcntl,json,sys
from pathlib import Path
import numpy as np
import torch
from torch.nn import functional as F
p=argparse.ArgumentParser();p.add_argument('--scene',required=True,choices=['ordinary','special']);a=p.parse_args();root=Path('/data/zhangbenzhuang/huawei_sr');out=root/'runs/SS928-SYSTEM-SPEED-20260926';sys.path[:0]=[str(Path(__file__).parent/'runtime'),'/tmp/packed_front_20260926/runtime',str(root/'runs/SS928-NIGHT-NINE-SPEED-20260926/runtime'),'/tmp'];from load_packed_model import load_packed_model;from system_variants import CompactReference
special=a.scene=='special';work='ss928-quality-special-night-nine-frame-20260925' if special else 'ss928-quality-night-nine-frame-20260925';run='SS928-QUALITY-SPECIAL-NIGHT-NINE-FRAME-20260925-2K-R1' if special else 'SS928-QUALITY-NIGHT-NINE-FRAME-TRAJECTORY-20260925-2K-R1';sys.path.insert(0,str(root/'code/worktrees'/work/'src'));from ir_sr.training import dataset_for_config
state=torch.load(root/'runs'/run/'checkpoints/step_000002000.pt',map_location='cpu',weights_only=False);ds=dataset_for_config(state['config'],'train');records=[r for r in ds.records if r['scene_id']=='night_'+a.scene];rows=[records[int(i)] for i in np.linspace(0,len(records)-1,min(32,len(records)),dtype=int)];lease=(root/'runs/TASK-019-gpu1.lock').open('a');fcntl.flock(lease,fcntl.LOCK_EX|fcntl.LOCK_NB);torch.set_num_threads(2);torch.backends.cuda.matmul.allow_tf32=False;torch.backends.cudnn.allow_tf32=False;torch.backends.cudnn.benchmark=True;torch.cuda.set_per_process_memory_fraction(2.5*1024**3/torch.cuda.get_device_properties(0).total_memory);rng=np.random.default_rng(933)
run=root/'runs'/('SS928-PACKED-FRONT-COMPACT8-20260926' if not special else 'SS928-PACKED-FRONT-20260926');step=json.loads((run/f'{a.scene}_selection.json').read_text())['selected_step'];base=load_packed_model(run/f'{a.scene}_packed_front_{step:06d}.pt',root/'runs/SS928-NIGHT-NINE-REFINE-20260926/selected_models'/f'{a.scene}_factor24.pt',root/'runs/SS928-NIGHT-NINE-SPEED-20260926/models'/f'{a.scene}_fused.pt');ck=torch.load(out/f'{a.scene}_reference_002000.pt',map_location='cpu',weights_only=True);student=CompactReference(ck['width']);student.load_state_dict(ck['reference']);student=student.cuda().half().to(memory_format=torch.channels_last);X=[];Y=[];DX=[];DY=[];meta=[]
with torch.inference_mode():
 for row in rows:
  ids=rng.integers(0,64*64,256);pair_x=[];pair_y=[]
  for frame in (max(0,row['frame_id']-1),row['frame_id']):
   rr=dict(row,frame_id=frame);ctx,_=ds.context_for(rr,crop_tlhw=(0,0,1024,1280));ctx=ctx[None].cuda();reference=base.core.model.global_reference;features=reference.encode(base.core.half_input(ctx));target=reference.project(features+features.mean((-2,-1),keepdim=True));hidden=F.relu(student.first(ctx.half()));patches=F.unfold(hidden.float(),3,padding=1)[0].cpu().numpy().astype(np.float64);design=(patches[:,ids]+patches.mean(1,keepdims=True)).T;values=target[0].reshape(16,-1)[:,ids].cpu().numpy().T;pair_x.append(design);pair_y.append(values)
  X.extend(pair_x);Y.extend(pair_y);DX.append(pair_x[1]-pair_x[0]);DY.append(pair_y[1]-pair_y[0]);meta.append({'sample_id':row['sample_id'],'frame_pair':[max(0,row['frame_id']-1),row['frame_id']],'split':'train'})
X=np.concatenate(X);Y=np.concatenate(Y);DX=np.concatenate(DX);DY=np.concatenate(DY);matrix=np.concatenate((X,DX),0);rhs=np.concatenate((Y,DY),0);matrix=np.concatenate((matrix,np.concatenate((np.full(len(X),2.),np.zeros(len(DX))))[:,None]),1);normal=matrix.T@matrix;right=matrix.T@rhs;records={}
for ridge_value in [1e-6,1e-4,.01]:
 ridge=np.eye(normal.shape[0])*ridge_value;ridge[-1,-1]=ridge_value*.01;coef=np.linalg.solve(normal+ridge,right);model=CompactReference(ck['width']);model.load_state_dict(ck['reference']);model.last.weight.data.copy_(torch.from_numpy(coef[:-1].T.reshape(16,ck['width'],3,3).astype(np.float32)));model.last.bias.data.copy_(torch.from_numpy(coef[-1].astype(np.float32)));tag=str(ridge_value);torch.save({'format':'compact_reference_v1','scene':a.scene,'width':ck['width'],'step':'postfit','reference':model.state_dict(),'GT_used':False,'ridge':ridge_value},out/f'{a.scene}_reference_postfit_{tag}.pt');records[tag]={'fit_feature_mae':float(np.abs(matrix@coef-rhs).mean()),'weight_norm':float(model.last.weight.norm()),'prior_weight_norm':float(student.last.weight.float().norm())};print('POSTFIT',a.scene,tag,records[tag],flush=True)
(out/f'{a.scene}_reference_postfit_training.json').write_text(json.dumps({'train_samples':meta,'GT_used':False,'records':records,'method':'last Conv3 + global mean exact linear least squares; pair temporal residuals; no new inference operators'},indent=2))
